# Generated by Django 4.0.3 on 2022-04-15 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carte_SIM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('Numéro_SIM', models.IntegerField()),
                ('Opérateur', models.CharField(max_length=35)),
                ('Créé_le', models.DateTimeField(auto_now_add=True)),
                ('Modifié_le', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Véhicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('Matricule', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=35)),
                ('Créé_le', models.DateTimeField(auto_now_add=True)),
                ('Modifié_le', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boitiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('Numéro_boitier', models.IntegerField()),
                ('Numéro_IMEM', models.IntegerField()),
                ('Fournisseur', models.CharField(max_length=50)),
                ('Créé_le', models.DateTimeField(auto_now_add=True)),
                ('Modifié_le', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
