# Generated by Django 4.0.3 on 2022-04-15 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='boitiers',
            name='version',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.version'),
        ),
    ]
