# Generated by Django 4.0.3 on 2022-05-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_affectation'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='Nom',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
