# Generated by Django 4.0.3 on 2022-05-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_affectation_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affectation',
            old_name='Nom',
            new_name='Numéro_aff',
        ),
        migrations.RemoveField(
            model_name='affectation',
            name='Numéro_affectation',
        ),
    ]
