# Generated by Django 4.0.3 on 2022-05-05 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_nom_affectation_numéro_aff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='Nom_Boitier',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.boitiers'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='Nom_SIM',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.carte_sim'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='Nom_Véhicule',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.véhicule'),
        ),
    ]
